O            ?= obj
HI           ?= hi
PROGRAM       = cre2c
GHCFLAGS     += -O2 -hidir $(HI) -odir $(O) -i$(O):$(HI) -rtsopts $(PROF)
GHCFLAGS     += -Wall -W -fno-warn-name-shadowing

HS_DEPENDS    = base containers dlist filepath hashable pretty process time unordered-containers
GHCFLAGS     += -hide-all-packages $(HS_DEPENDS:%=-package=%)

HAPPY_SOURCES       = RegexpParser.y SourceParser.y
HAPPY_AUTOGENERATED = $(HAPPY_SOURCES:%.y=%.hs)
HAPPY_OBJECTS       = $(HAPPY_SOURCES:%.y=$(O)/%.o)
HAPPY_INTERFACES    = $(HAPPY_SOURCES:%.y=$(HI)/%.hi)

SOURCES             = Types.hs CFA.hs RE2CFA.hs CFA2CPP.hs $(HAPPY_AUTOGENERATED)
OBJECTS             = $(SOURCES:%.hs=$(O)/%.o) Main.o
INTERFACES          = $(SOURCES:%.hs=$(HI)/%.hi) Main.hi
DEPS                = $(SOURCES:%.hs=$(O)/%.d) Main.d



all: $(PROGRAM)

$(PROGRAM): $(HAPPY_AUTOGENERATED)
	ghc --make $(GHCFLAGS) cre2c.hs

%.hs: %.y
	happy -o $@ $< || rm $@




.PHONY: clean clean_happy clean_all

clean:
	-rm -fv $(OBJECTS) $(INTERFACES) $(PROGRAM)

clean_happy:
	-rm -fv $(HAPPY_AUTOGENERATED) $(HAPPY_OBJECTS) $(HAPPY_INTERFACES) $(PROGRAM)

clean_all:
	-rm -fv $(HAPPY_AUTOGENERATED) $(HAPPY_OBJECTS) $(HAPPY_INTERFACES) $(OBJECTS) $(INTERFACES) $(PROGRAM)


-include $(DEPS)


.SUFFIXES:

.PRECIOUS: $(HAPPY_AUTOGENERATED)


